# Generated by Django 6.0.1 on 2026-02-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_seed_bank_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="수령인"
            ),
        ),
    ]
