# Generated by Django 6.0.1 on 2026-02-05 04:17

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "image1",
                    models.ImageField(
                        help_text="대표 이미지 (필수)",
                        upload_to=shop.models.product_image_upload_to,
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_image_upload_to,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_image_upload_to,
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_image_upload_to,
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_image_upload_to,
                    ),
                ),
                (
                    "description_text1",
                    models.TextField(blank=True, help_text="상세 설명 첫 번째 문단"),
                ),
                (
                    "description_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_detail_image_upload_to,
                    ),
                ),
                (
                    "description_text2",
                    models.TextField(blank=True, help_text="상세 설명 두 번째 문단"),
                ),
                (
                    "description_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.product_detail_image_upload_to,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="구매 수량"),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="결제시 상품명",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("IN", "입금"), ("OUT", "출금")], max_length=3
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("merchant", models.CharField(blank=True, max_length=50, null=True)),
                ("memo", models.CharField(blank=True, max_length=600, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
