# Generated by Django 6.0.1 on 2026-02-06 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="수령인"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="shipping_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="배송지 주소"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="shipping_detail_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="배송지 상세주소"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="shipping_zip_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="우편번호"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("content", models.TextField(verbose_name="리뷰 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
