# Generated by Django 6.0.1 on 2026-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='수령인'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='배송지 주소'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_detail_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='배송지 상세주소'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호'),
        ),
    ]
