# Generated by Django 6.0.1 on 2026-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_transaction_receiver_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
