# Generated by Django 6.0.1 on 2026-01-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('IN', '구매'), ('OUT', '환불')], max_length=3),
        ),
    ]
