# Generated by Django 6.0.1 on 2026-02-10 04:34

import django.db.models.deletion
import django.utils.timezone
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_transaction_receipt_hidden"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("amount", "정액 할인 (원)"),
                            ("percentage", "정률 할인 (%)"),
                        ],
                        default="amount",
                        max_length=10,
                    ),
                ),
                ("discount_value", models.PositiveIntegerField()),
                ("min_purchase_amount", models.PositiveIntegerField(default=0)),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=14, verbose_name="할인 금액"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_price_at_pay",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=14, verbose_name="할인 전 원가"
            ),
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=shop.models.review_image_upload_to,
                        verbose_name="리뷰 이미지",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="used_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.usercoupon",
                verbose_name="사용된 쿠폰",
            ),
        ),
    ]
