# Generated by Django 6.0.1 on 2026-02-10 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='할인 금액'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price_at_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='할인 전 원가'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='used_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.usercoupon', verbose_name='사용된 쿠폰'),
        ),
    ]
