# Generated by Django 6.0.1 on 2026-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
