# Generated by Django 6.0.1 on 2026-01-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image2',
        ),
        migrations.AddField(
            model_name='product',
            name='description_image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/desc/'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/desc/'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_text1',
            field=models.TextField(blank=True, help_text='상세 설명 첫 번째 문단'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_text2',
            field=models.TextField(blank=True, help_text='상세 설명 두 번째 문단'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=1, help_text='대표 이미지 (필수)', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
