# Generated by Django 6.0.1 on 2026-02-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_account_account_number_alter_account_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
