# Generated by Django 6.0.1 on 2026-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_account_is_default'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='uniq_user_account_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_default',
        ),
    ]
