# Generated by Django 6.0.1 on 2026-02-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_account_uniq_user_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_len', models.PositiveSmallIntegerField()),
                ('max_len', models.PositiveSmallIntegerField()),
                ('prefixes_csv', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='shop.bank'),
            preserve_default=False,
        ),
    ]
