# Generated by Django 6.0.1 on 2026-02-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_seed_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='구매 수량'),
        ),
    ]
